# Base16 Porple - wezterm color config
# Scheme by Niek den Breeje (https://github.com/AuditeMarlow)
[colors]
background = "#292c36"
foreground = "#d8d8d8"

cursor_bg = "#292c36"
cursor_border = "#d8d8d8"
cursor_fg = "#292c36"

selection_bg = "#d8d8d8"
selection_fg = "#292c36"

ansi = ["#292c36", "#f84547", "#95c76f", "#efa16b", "#8485ce", "#b74989", "#64878f", "#d8d8d8"]
brights = ["#65568a", "#d28e5d", "#333344", "#474160", "#b8b8b8", "#e8e8e8", "#986841", "#f8f8f8"]
