# Base16 Bespin - wezterm color config
# Scheme by Jan T. Sott
[colors]
background = "#28211c"
foreground = "#8a8986"

cursor_bg = "#28211c"
cursor_border = "#8a8986"
cursor_fg = "#28211c"

selection_bg = "#8a8986"
selection_fg = "#28211c"

ansi = ["#28211c", "#cf6a4c", "#54be0d", "#f9ee98", "#5ea6ea", "#9b859d", "#afc4db", "#8a8986"]
brights = ["#666666", "#cf7d34", "#36312e", "#5e5d5c", "#797977", "#9d9b97", "#937121", "#baae9e"]
