# Base16 Dark Violet - wezterm color config
# Scheme by ruler501 (https://github.com/ruler501/base16-darkviolet)
[colors]
background = "#000000"
foreground = "#b08ae6"

cursor_bg = "#000000"
cursor_border = "#b08ae6"
cursor_fg = "#000000"

selection_bg = "#b08ae6"
selection_fg = "#000000"

ansi = ["#000000", "#a82ee6", "#4595e6", "#f29df2", "#4136d9", "#7e5ce6", "#40dfff", "#b08ae6"]
brights = ["#593380", "#bb66cc", "#231a40", "#432d59", "#00ff00", "#9045e6", "#a886bf", "#a366ff"]
