# Base16 Hardcore - wezterm color config
# Scheme by Chris Caller
[colors]
background = "#212121"
foreground = "#cdcdcd"

cursor_bg = "#212121"
cursor_border = "#cdcdcd"
cursor_fg = "#212121"

selection_bg = "#cdcdcd"
selection_fg = "#212121"

ansi = ["#212121", "#f92672", "#a6e22e", "#e6db74", "#66d9ef", "#9e6ffe", "#708387", "#cdcdcd"]
brights = ["#4A4A4A", "#fd971f", "#303030", "#353535", "#707070", "#e5e5e5", "#e8b882", "#ffffff"]
