# Base16 Framer - wezterm color config
# Scheme by Framer (Maintained by Jesse Hoyos)
[colors]
background = "#181818"
foreground = "#D0D0D0"

cursor_bg = "#181818"
cursor_border = "#D0D0D0"
cursor_fg = "#181818"

selection_bg = "#D0D0D0"
selection_fg = "#181818"

ansi = ["#181818", "#FD886B", "#32CCDC", "#FECB6E", "#20BCFC", "#BA8CFC", "#ACDDFD", "#D0D0D0"]
brights = ["#747474", "#FC4769", "#151515", "#464646", "#B9B9B9", "#E8E8E8", "#B15F4A", "#EEEEEE"]
