# Base16 Silk Dark - wezterm color config
# Scheme by Gabriel Fontes (https://github.com/Misterio77)
[colors]
background = "#0e3c46"
foreground = "#C7DBDD"

cursor_bg = "#0e3c46"
cursor_border = "#C7DBDD"
cursor_fg = "#0e3c46"

selection_bg = "#C7DBDD"
selection_fg = "#0e3c46"

ansi = ["#0e3c46", "#fb6953", "#73d8ad", "#fce380", "#46bddd", "#756b8a", "#3fb2b9", "#C7DBDD"]
brights = ["#587073", "#fcab74", "#1D494E", "#2A5054", "#9DC8CD", "#CBF2F7", "#9b647b", "#D2FAFF"]
