# Base16 Woodland - wezterm color config
# Scheme by Jay Cornwall (https://jcornwall.com)
[colors]
background = "#231e18"
foreground = "#cabcb1"

cursor_bg = "#231e18"
cursor_border = "#cabcb1"
cursor_fg = "#231e18"

selection_bg = "#cabcb1"
selection_fg = "#231e18"

ansi = ["#231e18", "#d35c5c", "#b7ba53", "#e0ac16", "#88a4d3", "#bb90e2", "#6eb958", "#cabcb1"]
brights = ["#9d8b70", "#ca7f32", "#302b25", "#48413a", "#b4a490", "#d7c8bc", "#b49368", "#e4d4c8"]
