# Base16 Atelier Forest - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#1b1918"
foreground = "#a8a19f"

cursor_bg = "#1b1918"
cursor_border = "#a8a19f"
cursor_fg = "#1b1918"

selection_bg = "#a8a19f"
selection_fg = "#1b1918"

ansi = ["#1b1918", "#f22c40", "#7b9726", "#c38418", "#407ee7", "#6666ea", "#3d97b8", "#a8a19f"]
brights = ["#766e6b", "#df5320", "#2c2421", "#68615e", "#9c9491", "#e6e2e0", "#c33ff3", "#f1efee"]
