# Base16 Snazzy - wezterm color config
# Scheme by Chawye Hsu (https://github.com/chawyehsu) based on Hyper Snazzy Theme (https://github.com/sindresorhus/hyper-snazzy)
[colors]
background = "#282a36"
foreground = "#e2e4e5"

cursor_bg = "#282a36"
cursor_border = "#e2e4e5"
cursor_fg = "#282a36"

selection_bg = "#e2e4e5"
selection_fg = "#282a36"

ansi = ["#282a36", "#ff5c57", "#5af78e", "#f3f99d", "#57c7ff", "#ff6ac1", "#9aedfe", "#e2e4e5"]
brights = ["#78787e", "#ff9f43", "#34353e", "#43454f", "#a5a5a9", "#eff0eb", "#b2643c", "#f1f1f0"]
