# Base16 Nebula - wezterm color config
# Scheme by Gabriel Fontes (https://github.com/Misterio77)
[colors]
background = "#22273b"
foreground = "#a4a6a9"

cursor_bg = "#22273b"
cursor_border = "#a4a6a9"
cursor_fg = "#22273b"

selection_bg = "#a4a6a9"
selection_fg = "#22273b"

ansi = ["#22273b", "#777abc", "#6562a8", "#4f9062", "#4d6bb6", "#716cae", "#226f68", "#a4a6a9"]
brights = ["#6e6f72", "#94929e", "#414f60", "#5a8380", "#87888b", "#c7c9cd", "#8c70a7", "#8dbdaa"]
