# Base16 Rosé Pine Moon - wezterm color config
# Scheme by Emilia Dunfelt &lt;sayhi@dunfelt.se&gt;
[colors]
background = "#232136"
foreground = "#e0def4"

cursor_bg = "#232136"
cursor_border = "#e0def4"
cursor_fg = "#232136"

selection_bg = "#e0def4"
selection_fg = "#232136"

ansi = ["#232136", "#ecebf0", "#ea9a97", "#f6c177", "#9ccfd8", "#c4a7e7", "#3e8fb0", "#e0def4"]
brights = ["#59546d", "#eb6f92", "#2a273f", "#393552", "#817c9c", "#f5f5f7", "#b9b9bc", "#d9d7e1"]
