# Base16 Horizon Light - wezterm color config
# Scheme by Michaël Ball (http://github.com/michael-ball/)
[colors]
background = "#FDF0ED"
foreground = "#403C3D"

cursor_bg = "#FDF0ED"
cursor_border = "#403C3D"
cursor_fg = "#FDF0ED"

selection_bg = "#403C3D"
selection_fg = "#FDF0ED"

ansi = ["#FDF0ED", "#F7939B", "#94E1B0", "#FBE0D9", "#DA103F", "#1D8991", "#DC3318", "#403C3D"]
brights = ["#BDB3B1", "#F6661E", "#FADAD1", "#F9CBBE", "#948C8A", "#302C2D", "#E58C92", "#201C1D"]
