# Base16 Ashes - wezterm color config
# Scheme by Jannik Siebert (https://github.com/janniks)
[colors]
background = "#1C2023"
foreground = "#C7CCD1"

cursor_bg = "#1C2023"
cursor_border = "#C7CCD1"
cursor_fg = "#1C2023"

selection_bg = "#C7CCD1"
selection_fg = "#1C2023"

ansi = ["#1C2023", "#C7AE95", "#95C7AE", "#AEC795", "#AE95C7", "#C795AE", "#95AEC7", "#C7CCD1"]
brights = ["#747C84", "#C7C795", "#393F45", "#565E65", "#ADB3BA", "#DFE2E5", "#C79595", "#F3F4F5"]
