# Base16 Grayscale Light - wezterm color config
# Scheme by Alexandre Gavioli (https://github.com/Alexx2/)
[colors]
background = "#f7f7f7"
foreground = "#464646"

cursor_bg = "#f7f7f7"
cursor_border = "#464646"
cursor_fg = "#f7f7f7"

selection_bg = "#464646"
selection_fg = "#f7f7f7"

ansi = ["#f7f7f7", "#7c7c7c", "#8e8e8e", "#a0a0a0", "#686868", "#747474", "#868686", "#464646"]
brights = ["#ababab", "#999999", "#e3e3e3", "#b9b9b9", "#525252", "#252525", "#5e5e5e", "#101010"]
