# Base16 Gruvbox dark, medium - wezterm color config
# Scheme by Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
[colors]
background = "#282828"
foreground = "#d5c4a1"

cursor_bg = "#282828"
cursor_border = "#d5c4a1"
cursor_fg = "#282828"

selection_bg = "#d5c4a1"
selection_fg = "#282828"

ansi = ["#282828", "#fb4934", "#b8bb26", "#fabd2f", "#83a598", "#d3869b", "#8ec07c", "#d5c4a1"]
brights = ["#665c54", "#fe8019", "#3c3836", "#504945", "#bdae93", "#ebdbb2", "#d65d0e", "#fbf1c7"]
