# Base16 Edge Dark - wezterm color config
# Scheme by cjayross (https://github.com/cjayross)
[colors]
background = "#262729"
foreground = "#b7bec9"

cursor_bg = "#262729"
cursor_border = "#b7bec9"
cursor_fg = "#262729"

selection_bg = "#b7bec9"
selection_fg = "#262729"

ansi = ["#262729", "#e77171", "#a1bf78", "#dbb774", "#73b3e7", "#d390e7", "#5ebaa5", "#b7bec9"]
brights = ["#3e4249", "#e77171", "#88909f", "#b7bec9", "#73b3e7", "#d390e7", "#5ebaa5", "#3e4249"]
