# Base16 Marrakesh - wezterm color config
# Scheme by Alexandre Gavioli (http://github.com/Alexx2/)
[colors]
background = "#201602"
foreground = "#948e48"

cursor_bg = "#201602"
cursor_border = "#948e48"
cursor_fg = "#201602"

selection_bg = "#948e48"
selection_fg = "#201602"

ansi = ["#201602", "#c35359", "#18974e", "#a88339", "#477ca1", "#8868b3", "#75a738", "#948e48"]
brights = ["#6c6823", "#b36144", "#302e00", "#5f5b17", "#86813b", "#ccc37a", "#b3588e", "#faf0a5"]
