# Base16 One Light - wezterm color config
# Scheme by Daniel Pfeifer (http://github.com/purpleKarrot)
[colors]
background = "#fafafa"
foreground = "#383a42"

cursor_bg = "#fafafa"
cursor_border = "#383a42"
cursor_fg = "#fafafa"

selection_bg = "#383a42"
selection_fg = "#fafafa"

ansi = ["#fafafa", "#ca1243", "#50a14f", "#c18401", "#4078f2", "#a626a4", "#0184bc", "#383a42"]
brights = ["#a0a1a7", "#d75f00", "#f0f0f1", "#e5e5e6", "#696c77", "#202227", "#986801", "#090a0b"]
