# Base16 Atelier Estuary - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#22221b"
foreground = "#929181"

cursor_bg = "#22221b"
cursor_border = "#929181"
cursor_fg = "#22221b"

selection_bg = "#929181"
selection_fg = "#22221b"

ansi = ["#22221b", "#ba6236", "#7d9726", "#a5980d", "#36a166", "#5f9182", "#5b9d48", "#929181"]
brights = ["#6c6b5a", "#ae7313", "#302f27", "#5f5e4e", "#878573", "#e7e6df", "#9d6c7c", "#f4f3ec"]
