# Base16 Pico - wezterm color config
# Scheme by PICO-8 (http://www.lexaloffle.com/pico-8.php)
[colors]
background = "#000000"
foreground = "#5f574f"

cursor_bg = "#000000"
cursor_border = "#5f574f"
cursor_fg = "#000000"

selection_bg = "#5f574f"
selection_fg = "#000000"

ansi = ["#000000", "#ff004d", "#00e756", "#fff024", "#83769c", "#ff77a8", "#29adff", "#5f574f"]
brights = ["#008751", "#ffa300", "#1d2b53", "#7e2553", "#ab5236", "#c2c3c7", "#ffccaa", "#fff1e8"]
