# Base16 Cupertino - wezterm color config
# Scheme by Defman21
[colors]
background = "#ffffff"
foreground = "#404040"

cursor_bg = "#ffffff"
cursor_border = "#404040"
cursor_fg = "#ffffff"

selection_bg = "#404040"
selection_fg = "#ffffff"

ansi = ["#ffffff", "#c41a15", "#007400", "#826b28", "#0000ff", "#a90d91", "#318495", "#404040"]
brights = ["#808080", "#eb8500", "#c0c0c0", "#c0c0c0", "#808080", "#404040", "#826b28", "#5e5e5e"]
