# Base16 Windows High Contrast Light - wezterm color config
# Scheme by Fergus Collins (https://github.com/C-Fergus)
[colors]
background = "#fcfcfc"
foreground = "#545454"

cursor_bg = "#fcfcfc"
cursor_border = "#545454"
cursor_fg = "#fcfcfc"

selection_bg = "#545454"
selection_fg = "#fcfcfc"

ansi = ["#fcfcfc", "#800000", "#008000", "#808000", "#000080", "#800080", "#008080", "#545454"]
brights = ["#c0c0c0", "#fcfc54", "#e8e8e8", "#d4d4d4", "#7e7e7e", "#2a2a2a", "#54fc54", "#000000"]
