# Base16 Equilibrium Light - wezterm color config
# Scheme by Carlo Abelli
[colors]
background = "#f5f0e7"
foreground = "#43474e"

cursor_bg = "#f5f0e7"
cursor_border = "#43474e"
cursor_fg = "#f5f0e7"

selection_bg = "#43474e"
selection_fg = "#f5f0e7"

ansi = ["#f5f0e7", "#d02023", "#637200", "#9d6f00", "#0073b5", "#4e66b6", "#007a72", "#43474e"]
brights = ["#73777f", "#bf3e05", "#e7e2d9", "#d8d4cb", "#5a5f66", "#2c3138", "#c42775", "#181c22"]
