# Base16 Heetch Light - wezterm color config
# Scheme by Geoffrey Teale (tealeg@gmail.com)
[colors]
background = "#feffff"
foreground = "#5a496e"

cursor_bg = "#feffff"
cursor_border = "#5a496e"
cursor_fg = "#feffff"

selection_bg = "#5a496e"
selection_fg = "#feffff"

ansi = ["#feffff", "#27d9d5", "#f80059", "#5ba2b6", "#47f9f5", "#bd0152", "#c33678", "#5a496e"]
brights = ["#9c92a8", "#bdb6c5", "#392551", "#7b6d8b", "#ddd6e5", "#470546", "#dedae2", "#190134"]
