# Base16 Helios - wezterm color config
# Scheme by Alex Meyer (https://github.com/reyemxela)
[colors]
background = "#1d2021"
foreground = "#d5d5d5"

cursor_bg = "#1d2021"
cursor_border = "#d5d5d5"
cursor_fg = "#1d2021"

selection_bg = "#d5d5d5"
selection_fg = "#1d2021"

ansi = ["#1d2021", "#d72638", "#88b92d", "#f19d1a", "#1e8bac", "#be4264", "#1ba595", "#d5d5d5"]
brights = ["#6f7579", "#eb8413", "#383c3e", "#53585b", "#cdcdcd", "#dddddd", "#c85e0d", "#e5e5e5"]
