# Base16 IR Black - wezterm color config
# Scheme by Timothée Poisot (http://timotheepoisot.fr)
[colors]
background = "#000000"
foreground = "#b5b3aa"

cursor_bg = "#000000"
cursor_border = "#b5b3aa"
cursor_fg = "#000000"

selection_bg = "#b5b3aa"
selection_fg = "#000000"

ansi = ["#000000", "#ff6c60", "#a8ff60", "#ffffb6", "#96cbfe", "#ff73fd", "#c6c5fe", "#b5b3aa"]
brights = ["#6c6c66", "#e9c062", "#242422", "#484844", "#918f88", "#d9d7cc", "#b18a3d", "#fdfbee"]
