# Base16 Horizon Dark - wezterm color config
# Scheme by Michaël Ball (http://github.com/michael-ball/)
[colors]
background = "#1C1E26"
foreground = "#CBCED0"

cursor_bg = "#1C1E26"
cursor_border = "#CBCED0"
cursor_fg = "#1C1E26"

selection_bg = "#CBCED0"
selection_fg = "#1C1E26"

ansi = ["#1C1E26", "#E93C58", "#EFAF8E", "#EFB993", "#DF5273", "#B072D1", "#24A8B4", "#CBCED0"]
brights = ["#6F6F70", "#E58D7D", "#232530", "#2E303E", "#9DA0A2", "#DCDFE4", "#E4A382", "#E3E6EE"]
