# Base16 Default Dark - wezterm color config
# Scheme by Chris Kempson (http://chriskempson.com)
[colors]
background = "#181818"
foreground = "#d8d8d8"

cursor_bg = "#181818"
cursor_border = "#d8d8d8"
cursor_fg = "#181818"

selection_bg = "#d8d8d8"
selection_fg = "#181818"

ansi = ["#181818", "#ab4642", "#a1b56c", "#f7ca88", "#7cafc2", "#ba8baf", "#86c1b9", "#d8d8d8"]
brights = ["#585858", "#dc9656", "#282828", "#383838", "#b8b8b8", "#e8e8e8", "#a16946", "#f8f8f8"]
