# Base16 Windows 95 Light - wezterm color config
# Scheme by Fergus Collins (https://github.com/C-Fergus)
[colors]
background = "#fcfcfc"
foreground = "#545454"

cursor_bg = "#fcfcfc"
cursor_border = "#545454"
cursor_fg = "#fcfcfc"

selection_bg = "#545454"
selection_fg = "#fcfcfc"

ansi = ["#fcfcfc", "#a80000", "#00a800", "#a85400", "#0000a8", "#a800a8", "#00a8a8", "#545454"]
brights = ["#a8a8a8", "#fcfc54", "#e0e0e0", "#c4c4c4", "#7e7e7e", "#2a2a2a", "#54fc54", "#000000"]
