# Base16 Equilibrium Gray Dark - wezterm color config
# Scheme by Carlo Abelli
[colors]
background = "#111111"
foreground = "#ababab"

cursor_bg = "#111111"
cursor_border = "#ababab"
cursor_fg = "#111111"

selection_bg = "#ababab"
selection_fg = "#111111"

ansi = ["#111111", "#f04339", "#7f8b00", "#bb8801", "#008dd1", "#6a7fd2", "#00948b", "#ababab"]
brights = ["#777777", "#df5923", "#1b1b1b", "#262626", "#919191", "#c6c6c6", "#e3488e", "#e2e2e2"]
