# Base16 Tomorrow - wezterm color config
# Scheme by Chris Kempson (http://chriskempson.com)
[colors]
background = "#ffffff"
foreground = "#4d4d4c"

cursor_bg = "#ffffff"
cursor_border = "#4d4d4c"
cursor_fg = "#ffffff"

selection_bg = "#4d4d4c"
selection_fg = "#ffffff"

ansi = ["#ffffff", "#c82829", "#718c00", "#eab700", "#4271ae", "#8959a8", "#3e999f", "#4d4d4c"]
brights = ["#8e908c", "#f5871f", "#e0e0e0", "#d6d6d6", "#969896", "#282a2e", "#a3685a", "#1d1f21"]
