# Base16 Google Light - wezterm color config
# Scheme by Seth Wright (http://sethawright.com)
[colors]
background = "#ffffff"
foreground = "#373b41"

cursor_bg = "#ffffff"
cursor_border = "#373b41"
cursor_fg = "#ffffff"

selection_bg = "#373b41"
selection_fg = "#ffffff"

ansi = ["#ffffff", "#CC342B", "#198844", "#FBA922", "#3971ED", "#A36AC7", "#3971ED", "#373b41"]
brights = ["#b4b7b4", "#F96A38", "#e0e0e0", "#c5c8c6", "#969896", "#282a2e", "#3971ED", "#1d1f21"]
