# Base16 Windows High Contrast - wezterm color config
# Scheme by Fergus Collins (https://github.com/C-Fergus)
[colors]
background = "#000000"
foreground = "#c0c0c0"

cursor_bg = "#000000"
cursor_border = "#c0c0c0"
cursor_fg = "#000000"

selection_bg = "#c0c0c0"
selection_fg = "#000000"

ansi = ["#000000", "#fc5454", "#54fc54", "#fcfc54", "#5454fc", "#fc54fc", "#54fcfc", "#c0c0c0"]
brights = ["#545454", "#808000", "#1C1C1C", "#383838", "#a2a2a2", "#dedede", "#008000", "#fcfcfc"]
