# Base16 Apathy - wezterm color config
# Scheme by Jannik Siebert (https://github.com/janniks)
[colors]
background = "#031A16"
foreground = "#81B5AC"

cursor_bg = "#031A16"
cursor_border = "#81B5AC"
cursor_fg = "#031A16"

selection_bg = "#81B5AC"
selection_fg = "#031A16"

ansi = ["#031A16", "#3E9688", "#883E96", "#3E4C96", "#96883E", "#4C963E", "#963E4C", "#81B5AC"]
brights = ["#2B685E", "#3E7996", "#0B342D", "#184E45", "#5F9C92", "#A7CEC8", "#3E965B", "#D2E7E4"]
