# Base16 Silk Light - wezterm color config
# Scheme by Gabriel Fontes (https://github.com/Misterio77)
[colors]
background = "#E9F1EF"
foreground = "#385156"

cursor_bg = "#E9F1EF"
cursor_border = "#385156"
cursor_fg = "#E9F1EF"

selection_bg = "#385156"
selection_fg = "#E9F1EF"

ansi = ["#E9F1EF", "#CF432E", "#6CA38C", "#CFAD25", "#39AAC9", "#6E6582", "#329CA2", "#385156"]
brights = ["#5C787B", "#D27F46", "#CCD4D3", "#90B7B6", "#4B5B5F", "#0e3c46", "#865369", "#D2FAFF"]
