# Base16 Twilight - wezterm color config
# Scheme by David Hart (https://github.com/hartbit)
[colors]
background = "#1e1e1e"
foreground = "#a7a7a7"

cursor_bg = "#1e1e1e"
cursor_border = "#a7a7a7"
cursor_fg = "#1e1e1e"

selection_bg = "#a7a7a7"
selection_fg = "#1e1e1e"

ansi = ["#1e1e1e", "#cf6a4c", "#8f9d6a", "#f9ee98", "#7587a6", "#9b859d", "#afc4db", "#a7a7a7"]
brights = ["#5f5a60", "#cda869", "#323537", "#464b50", "#838184", "#c3c3c3", "#9b703f", "#ffffff"]
