# Base16 Monokai - wezterm color config
# Scheme by Wimer Hazenberg (http://www.monokai.nl)
[colors]
background = "#272822"
foreground = "#f8f8f2"

cursor_bg = "#272822"
cursor_border = "#f8f8f2"
cursor_fg = "#272822"

selection_bg = "#f8f8f2"
selection_fg = "#272822"

ansi = ["#272822", "#f92672", "#a6e22e", "#f4bf75", "#66d9ef", "#ae81ff", "#a1efe4", "#f8f8f2"]
brights = ["#75715e", "#fd971f", "#383830", "#49483e", "#a59f85", "#f5f4f1", "#cc6633", "#f9f8f5"]
