# Base16 Sakura - wezterm color config
# Scheme by Misterio77 (http://github.com/Misterio77)
[colors]
background = "#feedf3"
foreground = "#564448"

cursor_bg = "#feedf3"
cursor_border = "#564448"
cursor_fg = "#feedf3"

selection_bg = "#564448"
selection_fg = "#feedf3"

ansi = ["#feedf3", "#df2d52", "#2e916d", "#c29461", "#006e93", "#5e2180", "#1d8991", "#564448"]
brights = ["#755f64", "#f6661e", "#f8e2e7", "#e0ccd1", "#665055", "#42383a", "#ba0d35", "#33292b"]
