# Base16 Gigavolt - wezterm color config
# Scheme by Aidan Swope (http://github.com/Whillikers)
[colors]
background = "#202126"
foreground = "#e9e7e1"

cursor_bg = "#202126"
cursor_border = "#e9e7e1"
cursor_fg = "#202126"

selection_bg = "#e9e7e1"
selection_fg = "#202126"

ansi = ["#202126", "#ff661a", "#f2e6a9", "#ffdc2d", "#40bfff", "#ae94f9", "#fb6acb", "#e9e7e1"]
brights = ["#a1d2e6", "#19f988", "#2d303d", "#5a576e", "#cad3ff", "#eff0f9", "#6187ff", "#f2fbff"]
