# Base16 Atelier Forest Light - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#f1efee"
foreground = "#68615e"

cursor_bg = "#f1efee"
cursor_border = "#68615e"
cursor_fg = "#f1efee"

selection_bg = "#68615e"
selection_fg = "#f1efee"

ansi = ["#f1efee", "#f22c40", "#7b9726", "#c38418", "#407ee7", "#6666ea", "#3d97b8", "#68615e"]
brights = ["#9c9491", "#df5320", "#e6e2e0", "#a8a19f", "#766e6b", "#2c2421", "#c33ff3", "#1b1918"]
