# Base16 Atelier Dune Light - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#fefbec"
foreground = "#6e6b5e"

cursor_bg = "#fefbec"
cursor_border = "#6e6b5e"
cursor_fg = "#fefbec"

selection_bg = "#6e6b5e"
selection_fg = "#fefbec"

ansi = ["#fefbec", "#d73737", "#60ac39", "#ae9513", "#6684e1", "#b854d4", "#1fad83", "#6e6b5e"]
brights = ["#999580", "#b65611", "#e8e4cf", "#a6a28c", "#7d7a68", "#292824", "#d43552", "#20201d"]
