# Base16 Atelier Savanna Light - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#ecf4ee"
foreground = "#526057"

cursor_bg = "#ecf4ee"
cursor_border = "#526057"
cursor_fg = "#ecf4ee"

selection_bg = "#526057"
selection_fg = "#ecf4ee"

ansi = ["#ecf4ee", "#b16139", "#489963", "#a07e3b", "#478c90", "#55859b", "#1c9aa0", "#526057"]
brights = ["#78877d", "#9f713c", "#dfe7e2", "#87928a", "#5f6d64", "#232a25", "#867469", "#171c19"]
