# Base16 XCode Dusk - wezterm color config
# Scheme by Elsa Gonsiorowski (https://github.com/gonsie)
[colors]
background = "#282B35"
foreground = "#939599"

cursor_bg = "#282B35"
cursor_border = "#939599"
cursor_fg = "#282B35"

selection_bg = "#939599"
selection_fg = "#282B35"

ansi = ["#282B35", "#B21889", "#DF0002", "#438288", "#790EAD", "#B21889", "#00A0BE", "#939599"]
brights = ["#686A71", "#786DC5", "#3D4048", "#53555D", "#7E8086", "#A9AAAE", "#C77C48", "#BEBFC2"]
