# Base16 Default Light - wezterm color config
# Scheme by Chris Kempson (http://chriskempson.com)
[colors]
background = "#f8f8f8"
foreground = "#383838"

cursor_bg = "#f8f8f8"
cursor_border = "#383838"
cursor_fg = "#f8f8f8"

selection_bg = "#383838"
selection_fg = "#f8f8f8"

ansi = ["#f8f8f8", "#ab4642", "#a1b56c", "#f7ca88", "#7cafc2", "#ba8baf", "#86c1b9", "#383838"]
brights = ["#b8b8b8", "#dc9656", "#e8e8e8", "#d8d8d8", "#585858", "#282828", "#a16946", "#181818"]
