# Base16 Isotope - wezterm color config
# Scheme by Jan T. Sott
[colors]
background = "#000000"
foreground = "#d0d0d0"

cursor_bg = "#000000"
cursor_border = "#d0d0d0"
cursor_fg = "#000000"

selection_bg = "#d0d0d0"
selection_fg = "#000000"

ansi = ["#000000", "#ff0000", "#33ff00", "#ff0099", "#0066ff", "#cc00ff", "#00ffff", "#d0d0d0"]
brights = ["#808080", "#ff9900", "#404040", "#606060", "#c0c0c0", "#e0e0e0", "#3300ff", "#ffffff"]
