# Base16 Tomorrow Night - wezterm color config
# Scheme by Chris Kempson (http://chriskempson.com)
[colors]
background = "#2d2d2d"
foreground = "#cccccc"

cursor_bg = "#2d2d2d"
cursor_border = "#cccccc"
cursor_fg = "#2d2d2d"

selection_bg = "#cccccc"
selection_fg = "#2d2d2d"

ansi = ["#2d2d2d", "#f2777a", "#99cc99", "#ffcc66", "#6699cc", "#cc99cc", "#66cccc", "#cccccc"]
brights = ["#999999", "#f99157", "#393939", "#515151", "#b4b7b4", "#e0e0e0", "#a3685a", "#ffffff"]
