# Base16 Circus - wezterm color config
# Scheme by Stephan Boyer (https://github.com/stepchowfun) and Esther Wang (https://github.com/ewang12)
[colors]
background = "#191919"
foreground = "#a7a7a7"

cursor_bg = "#191919"
cursor_border = "#a7a7a7"
cursor_fg = "#191919"

selection_bg = "#a7a7a7"
selection_fg = "#191919"

ansi = ["#191919", "#dc657d", "#84b97c", "#c3ba63", "#639ee4", "#b888e2", "#4bb1a7", "#a7a7a7"]
brights = ["#5f5a60", "#4bb1a7", "#202020", "#303030", "#505050", "#808080", "#b888e2", "#ffffff"]
