# Base16 Github - wezterm color config
# Scheme by Defman21
[colors]
background = "#ffffff"
foreground = "#333333"

cursor_bg = "#ffffff"
cursor_border = "#333333"
cursor_fg = "#ffffff"

selection_bg = "#333333"
selection_fg = "#ffffff"

ansi = ["#ffffff", "#ed6a43", "#183691", "#795da3", "#795da3", "#a71d5d", "#183691", "#333333"]
brights = ["#969896", "#0086b3", "#f5f5f5", "#c8c8fa", "#e8e8e8", "#ffffff", "#333333", "#ffffff"]
