# Base16 Atelier Plateau Light - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
[colors]
background = "#f4ecec"
foreground = "#585050"

cursor_bg = "#f4ecec"
cursor_border = "#585050"
cursor_fg = "#f4ecec"

selection_bg = "#585050"
selection_fg = "#f4ecec"

ansi = ["#f4ecec", "#ca4949", "#4b8b8b", "#a06e3b", "#7272ca", "#8464c4", "#5485b6", "#585050"]
brights = ["#7e7777", "#b45a3c", "#e7dfdf", "#8a8585", "#655d5d", "#292424", "#bd5187", "#1b1818"]
