# Base16 darkmoss - wezterm color config
# Scheme by Gabriel Avanzi (https://github.com/avanzzzi)
[colors]
background = "#171e1f"
foreground = "#c7c7a5"

cursor_bg = "#171e1f"
cursor_border = "#c7c7a5"
cursor_fg = "#171e1f"

selection_bg = "#c7c7a5"
selection_fg = "#171e1f"

ansi = ["#171e1f", "#ff4658", "#499180", "#fdb11f", "#498091", "#9bc0c8", "#66d9ef", "#c7c7a5"]
brights = ["#555e5f", "#e6db74", "#252c2d", "#373c3d", "#818f80", "#e3e3c8", "#d27b53", "#e1eaef"]
