# Base16 Material Lighter - wezterm color config
# Scheme by Nate Peterson
[colors]
background = "#FAFAFA"
foreground = "#80CBC4"

cursor_bg = "#FAFAFA"
cursor_border = "#80CBC4"
cursor_fg = "#FAFAFA"

selection_bg = "#80CBC4"
selection_fg = "#FAFAFA"

ansi = ["#FAFAFA", "#FF5370", "#91B859", "#FFB62C", "#6182B8", "#7C4DFF", "#39ADB5", "#80CBC4"]
brights = ["#CCD7DA", "#F76D47", "#E7EAEC", "#CCEAE7", "#8796B0", "#80CBC4", "#E53935", "#FFFFFF"]
